# Generated by Django 4.1.6 on 2023-04-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('address', models.TextField()),
                ('user_type', models.CharField(choices=[('M', 'Manufacturer'), ('R', 'Retailer')], max_length=15)),
                ('image', models.ImageField(upload_to='static/user_images')),
            ],
        ),
    ]
